version: "3.9"

services:
  app:
    build: ./app
    ports:
      - 5173:5173
      - 3010:3010
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: developpement
      VITE_API_URL: http://localhost:3000
      JWT_SECRET: secret
    depends_on:
      - api

  api:
    build: ./api
    ports:
      - 3000:3000
    volumes:
      - ./api:/usr/src/api
      - /usr/src/api/node_modules
    environment:
      NODE_ENV: developpement
      MONGO_URI: mongodb://passi:example@mongo:27017/
      PORT: 3000
      JWT_SECRET: secret
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: passi
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./data:/data/db
      - ./pastries/pastries.json:/usr/src/pastries.json

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: passi
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://passi:example@mongo:27017/
      ME_CONFIG_BASICAUTH: "false"
